---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    self_contained: no
    css: ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css", "rlinecounter.css"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shinyWidgets)
library(htmltools)
library(shiny)
rmarkdown::html_dependency_jquery()
rmarkdown::html_dependency_bootstrap("spacelab")
rmarkdown::html_dependency_jqueryui()
```

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

Intro 
=======================================================================

Row
-----------------------------------------------------------------------

Coursework 
=======================================================================

Row
-----------------------------------------------------------------------
```{r}
Coursework <- list(Test1 = "Test", Test2 = "Test")
```

```{r}
tags$style('#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active .fa{background-color: #112446;background-image: #112446 !important;}
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu.vrtc-tab-panel-menu-left div.list-group>a.active:after{border-left: 10px solid #112446 !important;}
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu.vrtc-tab-panel-menu-right div.list-group>a.active:after{border-right: 10px solid #112446 !important;}
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu div.list-group>a .glyphicon,
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu div.list-group>a .fa {color: #112446 !important;}
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active,
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active .glyphicon,
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu div.list-group>a.active .fa{
background-color: #112446 !important; background-image: #112446 !important; color: #ffffff !important;
}
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu.vrtc-tab-panel-menu-left div.list-group>a.active:after{border-left: 10px solid #112446 !important;}
#sryUSuOXwLuqNkKgmhmdHTOP-tabbable > div.vrtc-tab-panel-menu.vrtc-tab-panel-menu-right div.list-group>a.active:after{border-right: 10px solid #112446 !important;}')
```



<div class="col-sm-12 vrtc-tab-panel-container tabbable" id="sryUSuOXwLuqNkKgmhmdHTOP-tabbable">
<div class="col-sm-2 vrtc-tab-panel-menu vrtc-tab-panel-menu-left">
<div class="list-group vertical-tab-panel" id="sryUSuOXwLuqNkKgmhmdHTOP"> active</div>
</div>
<div class="col-sm-10 vrtc-tab-panel  tab-content"> active</div>
</div>
```{r, results='asis', eval = F}

verticalTabsetPanel(selected = "Test1", contentWidth = 10,
  tagList(
    purrr::imap(Coursework, ~ {
        verticalTabPanel(title = .y)
      })
  )
)
```

